export const CARDS = [
  'Pijesz 1x.',
  'Pijesz 2x.',
  'Wszyscy piją oprócz ciebie.',
  'Wszyscy piją.',
  'Każesz jakiejś osobie wypić 1x.',
  'Robisz 10 pompek i pijesz 1x albo ich nie robisz i pijesz 2x.',
  'Pijesz 1x ty i osoba po twojej prawej i lewej.',
  'Dostajesz 200$ od banku.',
  'Dostajesz 100$ od każdego, chyba że ten wypije 1x.',
  'Płacisz 100$.',
  'Płacisz każdemu po 50$, który wypije twoje zdrowie.',
  'Za każdego wypitego dostajesz po 100$ od banku.',
  'Najbogatsza osoba płaci 100$ najbiedniejszej i pije jej zdrowie.',
  'Nie pijesz przez dwie następne okazje.',
  'Wywieźli cię na pole start.',
  'Wywieźli cię do szpitala.',
  'Wywieźli cię na wytrzeźwialke.',
  'Wywieźli cię na ryneczek.',
  // 'Idziesz na jakies miasto dla co drugiego miasta ta karta bedzie czyli 8x',
];
