import type { Place } from '../types';

export const PLACES: Place[] = [
  { name: 'Start', type: 'go' },
  { name: 'FoodForYou', type: 'property', price: 50 },
  { name: 'Karta', type: 'card' },
  { name: 'Altany', type: 'property', price: 50 },
  { name: 'PKP Bełsznica', type: 'specialProperty', price: 150 },
  { name: 'Owsiszcze', type: 'property', price: 60 },
  { name: 'Wszyscy pijom', type: 'allDrinks' },
  { name: 'Familoki', type: 'property', price: 60 },
  { name: 'Ryneczek', type: 'square' },
  { name: 'Dingo', type: 'property', price: 80 },
  { name: 'Karta', type: 'card' },
  { name: 'Biedronka', type: 'property', price: 80 },
  { name: 'PKP Czyżowice', type: 'specialProperty', price: 150 },
  { name: 'Zmyrzlina', type: 'property', price: 90 },
  { name: 'Balaton', type: 'property', price: 90 },
  { name: 'Kaliszczok', type: 'property', price: 90 },
  { name: 'Wytrzeźwialka', type: 'prison' },
  { name: 'Gomola', type: 'property', price: 110 },
  { name: 'Karta', type: 'card' },
  { name: 'Megol', type: 'property', price: 110 },
  { name: 'PKP Chałupki', type: 'specialProperty', price: 150 },
  { name: 'Megok Olza', type: 'property', price: 120 },
  { name: 'Wszyscy pijom', type: 'allDrinks' },
  { name: 'Megok Gorzyce', type: 'property', price: 120 },
  { name: 'WOLO', type: 'hospital' },
  { name: 'Strych', type: 'property', price: 140 },
  { name: 'Karta', type: 'card' },
  { name: 'Piwnica', type: 'property', price: 140 },
  { name: 'PKP Wodzisław', type: 'specialProperty', price: 150 },
  { name: 'Stodoła', type: 'property', price: 150 },
  { name: 'Koń', type: 'property', price: 150 },
  { name: 'Akacjowa 16', type: 'property', price: 150 },
];
