import { Place, PlaceType } from '../types';

export const PLACES: Place[] = [
  { name: 'Start', type: PlaceType.GO },
  { name: 'Small lake', type: PlaceType.PROPERTY, price: 50 },
  { name: 'Card', type: PlaceType.CARD },
  { name: 'Skatepark', type: PlaceType.PROPERTY, price: 50 },
  { name: 'Tram stop', type: PlaceType.SPECIAL_PROPERTY, price: 150 },
  { name: 'Park', type: PlaceType.PROPERTY, price: 60 },
  { name: 'Everyone is drinking', type: PlaceType.ALL_DRINKS },
  { name: "McDonald's", type: PlaceType.PROPERTY, price: 60 },
  { name: 'Square', type: PlaceType.SQUARE },
  { name: 'Subway', type: PlaceType.PROPERTY, price: 80 },
  { name: 'Card', type: PlaceType.CARD },
  { name: 'KFC', type: PlaceType.PROPERTY, price: 80 },
  { name: 'Bus stop', type: PlaceType.SPECIAL_PROPERTY, price: 150 },
  { name: 'Burger King', type: PlaceType.PROPERTY, price: 90 },
  { name: 'Local shop', type: PlaceType.PROPERTY, price: 90 },
  { name: 'Games room', type: PlaceType.PROPERTY, price: 90 },
  { name: 'Prison', type: PlaceType.PRISON },
  { name: 'Gas station', type: PlaceType.PROPERTY, price: 110 },
  { name: 'Card', type: PlaceType.CARD },
  { name: 'Supermarket', type: PlaceType.PROPERTY, price: 110 },
  { name: 'Train stop', type: PlaceType.SPECIAL_PROPERTY, price: 150 },
  { name: 'Bar', type: PlaceType.PROPERTY, price: 120 },
  { name: 'Everyone is drinking', type: PlaceType.ALL_DRINKS },
  { name: 'Marijuana farm', type: PlaceType.PROPERTY, price: 120 },
  { name: 'Hospital', type: PlaceType.HOSPITAL },
  { name: 'Moonshine production', type: PlaceType.PROPERTY, price: 140 },
  { name: 'Card', type: PlaceType.CARD },
  { name: 'Club', type: PlaceType.PROPERTY, price: 140 },
  { name: 'Subway stop', type: PlaceType.SPECIAL_PROPERTY, price: 150 },
  { name: 'Strip club', type: PlaceType.PROPERTY, price: 150 },
  { name: 'Casino ', type: PlaceType.PROPERTY, price: 150 },
  { name: 'Liquor store', type: PlaceType.PROPERTY, price: 150 },
];
